INSERT INTO member (email,first_name,last_name,gender,level,preferred_gym_location,budget,focus1,focus2,focus3) VALUES
    ('knortham0@weather.com','Kim','Northam','F','Beginner','North',52,'Running','Crossfit','Pilates'),
    ('rreynolds1@wordpress.com','Robbert','Reynolds','M','Advanced','North',100,'Martial Arts','Pilates','Powerlifting'),
    ('sreinger2@techcrunch.com','Stern','Reinger','M','Advanced','South',99,'Running','Spin','Calisthenics'),
    ('pmacguiness3@statcounter.com','Parry','MacGuiness','M','Intermediate','East',131,'Running','Spin','Swimming'),
    ('fdekeyser4@fastcompany.com','Frederico','Dekeyser','M','Intermediate','West',145,'Weightlifting','Spin','Pilates'),
    ('jraiman5@nhs.uk','Jyoti','Raiman','F','Advanced','North',53,'Running','Crossfit','Powerlifting'),
    ('kastin6@forbes.com','Kissee','Astin','F','Beginner','Central',163,'Spin','Powerlifting','Pilates'),
    ('ncahani7@usnews.com','Nickola','Cahani','M','Beginner','Central',103,'Weightlifting','Powerlifting','Calisthenics'),
    ('dshinner8@ebay.com','Donnamarie','Shinner','F','Beginner','South',147,'Physiotherapy','Martial Arts','Calisthenics'),
    ('cbranigan9@is.gd','Cacilie','Branigan','F','Beginner','Central',179,'Weightlifting','Crossfit','Yoga'),
    ('rcroucha@a8.net','Regine','Crouch','F','Intermediate','South',86,'Spin','Pilates','Physiotherapy'),
    ('nwickendenb@bbb.org','Noah','Wickenden','M','Intermediate','West',187,'Powerlifting','Running','Weightlifting'),
    ('ekollaschc@statcounter.com','Ernaline','Kollasch','F','Advanced','East',186,'Calisthenics','Spin','Swimming'),
    ('jmcconnelld@163.com','Janel','McConnell','F','Intermediate','South',190,'Martial Arts','Physiotherapy','Spin'),
    ('dchattertone@webnode.com','Dell','Chatterton','F','Advanced','East',158,'Powerlifting','Weightlifting','Yoga'),
    ('arozzellf@xrea.com','Aube','Rozzell','M','Intermediate','Central',131,'Swimming','Weightlifting','Calisthenics'),
    ('ccardozog@nih.gov','Corrinne','Cardozo','F','Intermediate','Central',61,'Physiotherapy','Swimming','Powerlifting'),
    ('abraisherh@flickr.com','Aili','Braisher','F','Beginner','South',129,'Physiotherapy','Running','Weightlifting'),
    ('alystoni@cnn.com','Anette','Lyston','F','Advanced','West',57,'Spin','Weightlifting','Physiotherapy'),
    ('amclellandj@posterous.com','Arlen','McLelland','M','Advanced','West',133,'Yoga','Crossfit','Pilates'),
    ('wcoshk@hud.gov','Way','Cosh','M','Beginner','East',137,'Yoga','Pilates','Physiotherapy'),
    ('cflorentinel@spiegel.de','Craggie','Florentine','M','Intermediate','Central',148,'Physiotherapy','Running','Weightlifting'),
    ('fokelleherm@pinterest.com','Fredericka','O'' Kelleher','F','Advanced','Central',107,'Calisthenics','Physiotherapy','Spin'),
    ('irudwelln@behance.net','Ingaborg','Rudwell','F','Beginner','East',66,'Spin','Yoga','Pilates'),
    ('apirolinio@google.ru','Ab','Pirolini','M','Intermediate','East',73,'Running','Yoga','Weightlifting'),
    ('alouchp@blogs.com','Adelind','Louch','F','Advanced','East',55,'Weightlifting','Running','Calisthenics'),
    ('kdrakeq@foxnews.com','Karon','Drake','F','Beginner','West',165,'Calisthenics','Powerlifting','Spin'),
    ('cgrosvenorr@uiuc.edu','Cam','Grosvenor','F','Intermediate','Central',124,'Pilates','Swimming','Crossfit'),
    ('hgiblins@kickstarter.com','Hildegarde','Giblin','F','Beginner','East',86,'Pilates','Physiotherapy','Weightlifting'),
    ('jhindricht@alexa.com','Joe','Hindrich','M','Intermediate','North',182,'Powerlifting','Martial Arts','Pilates'),
    ('odemciku@elpais.com','Osborn','Demcik','M','Beginner','Central',71,'Powerlifting','Weightlifting','Yoga'),
    ('tshillingtonv@eepurl.com','Torrie','Shillington','F','Beginner','East',127,'Weightlifting','Martial Arts','Crossfit'),
    ('jroskeillyw@engadget.com','Johna','Roskeilly','F','Intermediate','North',107,'Spin','Martial Arts','Yoga'),
    ('sevenettx@scientificamerican.com','Sammie','Evenett','M','Intermediate','West',173,'Spin','Yoga','Pilates'),
    ('flilleymany@4shared.com','Fransisco','Lilleyman','M','Beginner','West',119,'Martial Arts','Crossfit','Swimming'),
    ('evolkez@artisteer.com','Emanuel','Volke','M','Advanced','South',102,'Weightlifting','Swimming','Powerlifting'),
    ('tsigars10@trellian.com','Thurston','Sigars','M','Advanced','North',71,'Running','Martial Arts','Swimming'),
    ('vkeelan11@blogspot.com','Vilma','Keelan','F','Beginner','West',70,'Running','Pilates','Spin'),
    ('jarminger12@google.com.hk','Justen','Arminger','M','Beginner','North',185,'Spin','Crossfit','Pilates'),
    ('kevert13@gmpg.org','Karlotte','Evert','F','Advanced','East',147,'Spin','Pilates','Weightlifting'),
    ('mwenderott14@photobucket.com','Melli','Wenderott','F','Advanced','East',84,'Pilates','Physiotherapy','Yoga'),
    ('revensden15@dell.com','Rustin','Evensden','M','Beginner','South',84,'Spin','Running','Crossfit'),
    ('aknuckles16@go.com','Alasteir','Knuckles','M','Advanced','North',61,'Physiotherapy','Spin','Swimming'),
    ('cdominguez17@ucsd.edu','Cesare','Dominguez','M','Beginner','East',86,'Running','Spin','Physiotherapy'),
    ('lpiwall18@mlb.com','Leela','Piwall','F','Intermediate','Central',192,'Physiotherapy','Running','Spin'),
    ('scampagne19@tiny.cc','Stevy','Campagne','M','Advanced','East',129,'Swimming','Calisthenics','Weightlifting'),
    ('achelam1a@npr.org','Anstice','Chelam','F','Beginner','West',179,'Powerlifting','Martial Arts','Spin'),
    ('lsteels1b@nydailynews.com','Leandra','Steels','F','Intermediate','West',86,'Calisthenics','Crossfit','Pilates'),
    ('sarger1c@bbc.co.uk','Siward','Arger','M','Intermediate','South',155,'Pilates','Spin','Running'),
    ('trewbottom1d@cloudflare.com','Torre','Rewbottom','M','Advanced','East',110,'Martial Arts','Physiotherapy','Running'),
    ('ballison1e@soundcloud.com','Bertie','Allison','F','Beginner','East',164,'Calisthenics','Weightlifting','Crossfit'),
    ('bgrimsley1f@myspace.com','Bucky','Grimsley','M','Intermediate','West',84,'Yoga','Spin','Martial Arts'),
    ('nhutcheson1g@newyorker.com','Nettle','Hutcheson','F','Beginner','Central',57,'Martial Arts','Running','Weightlifting'),
    ('hephgrave1h@geocities.jp','Hestia','Ephgrave','F','Intermediate','East',52,'Swimming','Running','Martial Arts'),
    ('dkettel1i@1und1.de','Dalis','Kettel','M','Intermediate','West',188,'Yoga','Calisthenics','Powerlifting'),
    ('gpickerill1j@miitbeian.gov.cn','Gilles','Pickerill','M','Intermediate','North',155,'Running','Calisthenics','Crossfit'),
    ('vstacy1k@google.ru','Vi','Stacy','F','Intermediate','Central',94,'Yoga','Swimming','Martial Arts'),
    ('econeybeer1l@hao123.com','Errol','Coneybeer','M','Intermediate','South',130,'Martial Arts','Yoga','Spin'),
    ('lmoggle1m@discuz.net','Lacy','Moggle','F','Beginner','East',150,'Weightlifting','Pilates','Yoga'),
    ('mleverett1n@microsoft.com','Margot','Leverett','F','Beginner','East',76,'Swimming','Yoga','Martial Arts'),
    ('gcleaves1o@tumblr.com','Glyn','Cleaves','M','Advanced','Central',89,'Martial Arts','Calisthenics','Weightlifting'),
    ('speron1p@hugedomains.com','Silvano','Peron','M','Intermediate','Central',55,'Spin','Crossfit','Physiotherapy'),
    ('jmunby1q@sphinn.com','Joelle','Munby','F','Beginner','East',124,'Spin','Yoga','Pilates'),
    ('hbricksey1r@exblog.jp','Hadrian','Bricksey','M','Advanced','East',136,'Swimming','Pilates','Powerlifting'),
    ('tlittrick1s@businessinsider.com','Tybie','Littrick','F','Advanced','East',122,'Powerlifting','Physiotherapy','Pilates'),
    ('lpruvost1t@bloglines.com','Lita','Pruvost','F','Advanced','East',94,'Pilates','Spin','Running'),
    ('adenisyuk1u@nytimes.com','Aile','Denisyuk','F','Beginner','South',56,'Spin','Calisthenics','Weightlifting'),
    ('dmatzeitis1v@php.net','Donny','Matzeitis','F','Intermediate','East',177,'Spin','Powerlifting','Pilates'),
    ('plondesborough1w@walmart.com','Priscilla','Londesborough','F','Advanced','West',193,'Running','Pilates','Crossfit'),
    ('lquakley1x@who.int','Lemmie','Quakley','M','Intermediate','South',144,'Physiotherapy','Powerlifting','Pilates'),
    ('forridge1y@liveinternet.ru','Fernande','Orridge','F','Beginner','South',86,'Spin','Powerlifting','Physiotherapy'),
    ('sclay1z@joomla.org','Seline','Clay','F','Intermediate','East',162,'Spin','Yoga','Martial Arts'),
    ('brohan20@storify.com','Booth','Rohan','M','Advanced','West',145,'Pilates','Spin','Martial Arts'),
    ('gperks21@hhs.gov','Geoff','Perks','M','Advanced','West',89,'Swimming','Spin','Weightlifting'),
    ('kpierucci22@skype.com','Kimble','Pierucci','M','Advanced','East',153,'Physiotherapy','Swimming','Martial Arts'),
    ('suttley23@biglobe.ne.jp','Sofia','Uttley','F','Intermediate','South',127,'Yoga','Powerlifting','Running'),
    ('lrymill24@arizona.edu','Lyn','Rymill','M','Beginner','Central',115,'Running','Spin','Physiotherapy'),
    ('clowensohn25@fema.gov','Cross','Lowensohn','M','Beginner','North',148,'Spin','Physiotherapy','Running'),
    ('fbennell26@umich.edu','Forster','Bennell','M','Beginner','West',179,'Crossfit','Powerlifting','Calisthenics'),
    ('pcoushe27@dedecms.com','Pandora','Coushe','F','Advanced','West',123,'Calisthenics','Crossfit','Yoga'),
    ('aprest28@arstechnica.com','Alexia','Prest','F','Beginner','South',150,'Spin','Powerlifting','Crossfit'),
    ('bblunkett29@indiatimes.com','Belia','Blunkett','F','Advanced','East',146,'Crossfit','Running','Calisthenics'),
    ('bboutton2a@accuweather.com','Brennen','Boutton','M','Intermediate','West',101,'Powerlifting','Physiotherapy','Running'),
    ('fmcmurdo2b@dion.ne.jp','Fielding','McMurdo','M','Intermediate','West',200,'Spin','Martial Arts','Swimming'),
    ('jquade2c@usa.gov','Jo ann','Quade','F','Intermediate','North',120,'Yoga','Calisthenics','Physiotherapy'),
    ('tfosdyke2d@tripod.com','Trixie','Fosdyke','F','Intermediate','Central',146,'Crossfit','Running','Martial Arts'),
    ('bharroway2e@over-blog.com','Bill','Harroway','F','Beginner','West',178,'Spin','Pilates','Yoga'),
    ('xloosely2f@google.com.br','Xena','Loosely','F','Intermediate','North',168,'Pilates','Swimming','Running'),
    ('rdrinkel2g@washington.edu','Rosco','Drinkel','M','Beginner','Central',200,'Powerlifting','Martial Arts','Calisthenics'),
    ('tashman2h@marriott.com','Tresa','Ashman','F','Intermediate','South',136,'Calisthenics','Running','Spin'),
    ('ascantlebury2i@ameblo.jp','Arlyn','Scantlebury','F','Advanced','Central',123,'Powerlifting','Swimming','Calisthenics'),
    ('chawtin2j@baidu.com','Carlynn','Hawtin','F','Intermediate','West',168,'Weightlifting','Yoga','Spin'),
    ('kdenisyev2k@list-manage.com','Kirstin','Denisyev','F','Advanced','South',57,'Powerlifting','Pilates','Physiotherapy'),
    ('hmogridge2l@independent.co.uk','Hestia','Mogridge','F','Advanced','West',142,'Pilates','Physiotherapy','Spin'),
    ('lmackro2m@marketwatch.com','Liuka','Mackro','F','Advanced','South',170,'Running','Yoga','Spin'),
    ('cjacobssen2n@wiley.com','Crawford','Jacobssen','M','Intermediate','West',195,'Physiotherapy','Running','Crossfit'),
    ('lkasman2o@gizmodo.com','Lauren','Kasman','M','Advanced','Central',83,'Weightlifting','Yoga','Running'),
    ('mkelberman2p@arizona.edu','Maurene','Kelberman','F','Advanced','East',70,'Weightlifting','Spin','Martial Arts'),
    ('dlibbie2q@wordpress.org','Drusilla','Libbie','F','Intermediate','Central',88,'Swimming','Running','Spin'),
    ('jedwick2r@cyberchimps.com','Janaya','Edwick','F','Advanced','South',61,'Martial Arts','Running','Powerlifting');