INSERT INTO trainer (email, first_name, last_name, gender, lower_price_range, upper_price_range,experience,focus1,focus2,focus3,level) VALUES
    ('smartinovic0@narod.ru','Sharity','Martinovic','F',44,100,2,'Crossfit','Martial Arts','Spin','Beginner'),
    ('gpavinese1@princeton.edu','Garnet','Pavinese','F',45,85,35,'Running','Martial Arts','Spin','Intermediate'),
    ('nturmel2@digg.com','Nathalie','Turmel','M',45,106,32,'Pilates','Physiotherapy','Powerlifting','Beginner'),
    ('kreary3@sina.com.cn','Kirsten','Reary','F',48,138,34,'Running','Pilates','Yoga','Beginner'),
    ('araynard4@apple.com','Abbey','Raynard','M',49,105,21,'Calisthenics','Running','Powerlifting','Intermediate'),
    ('dgipp5@walmart.com','Darryl','Gipp','F',48,122,1,'Powerlifting','Running','Yoga','Advanced'),
    ('cdevries6@a8.net','Conroy','De Vries','F',40,131,41,'Calisthenics','Running','Martial Arts','Beginner'),
    ('fsoars7@mozilla.org','Faustina','Soars','F',44,142,48,'Running','Calisthenics','Powerlifting','Intermediate'),
    ('frooze8@altervista.org','Fletcher','Rooze','M',41,93,7,'Martial Arts','Pilates','Physiotherapy','Beginner'),
    ('emcaless9@elegantthemes.com','Ewan','McAless','F',42,150,47,'Running','Swimming','Weighlifting','Intermediate'),
    ('igatteridgea@seesaa.net','Ingemar','Gatteridge','F',41,117,39,'Martial Arts','Yoga','Weightlifting','Beginner'),
    ('rsteffansb@sciencedaily.com','Ringo','Steffans','F',48,132,19,'Martial Arts','Physiotherapy','Pilates','Advanced'),
    ('wmynerc@si.edu','Welbie','Myner','F',50,148,0,'Martial Arts','Swimming','Weightlifting','Beginner'),
    ('fradeliffed@independent.co.uk','Fons','Radeliffe','M',41,108,48,'Pilates','Yoga','Weightlifting','Advanced'),
    ('niacovazzie@blogspot.com','Nat','Iacovazzi','F',46,135,16,'Powerlifting','Swimming','Spin','Advanced'),
    ('cvatcherf@hp.com','Culley','Vatcher','M',49,140,42,'Powerlifting','Crossfit','Calisthenics','Beginner'),
    ('hboundyg@senate.gov','Hort','Boundy','F',44,91,45,'Weightlifting','Running','Martial Arts','Intermediate'),
    ('bgreenroadh@devhub.com','Briana','Greenroad','F',45,140,16,'Martial Arts','Swimming','Spin','Intermediate'),
    ('mmaygeri@irs.gov','Monte','Mayger','M',42,100,35,'Martial Arts','Powerlifting','Pilates','Intermediate'),
    ('dadshedj@harvard.edu','Dagmar','Adshed','M',50,147,34,'Martial Arts','Pilates','Spin','Intermediate'),
    ('sdunnettk@chron.com','Sully','Dunnett','F',41,82,38,'Physiotherapy','Running','Martial Arts','Beginner'),
    ('pfudgel@google.co.jp','Page','Fudge','F',45,148,49,'Powerlifting','Running','Weightlifting','Advanced'),
    ('kjarrattm@google.co.uk','Karlie','Jarratt','M',48,139,17,'Physiotherapy','Powerlifting','Martial Arts','Intermediate'),
    ('fdixceyn@indiegogo.com','Felicio','Dixcey','F',47,81,18,'Powerlifting','Martial Arts','Spin','Intermediate'),
    ('egoodeo@google.co.uk','Emlyn','Goode','M',44,139,9,'Running','Pilates','Powerlifting','Advanced'),
    ('tlongstaffep@independent.co.uk','Trixi','Longstaffe','M',46,81,38,'Running','Weightlifting','Yoga','Beginner'),
    ('dhrihorovichq@ehow.com','Darb','Hrihorovich','M',45,100,5,'Physiotherapy','Running','Weightlifting','Advanced'),
    ('vholdeyr@ameblo.jp','Viviana','Holdey','F',49,111,22,'Martial Arts','Swimming','Calisthenics','Intermediate'),
    ('scadremans@bravesites.com','Shelley','Cadreman','M',45,109,33,'Weightlifting','Physiotherapy','Running','Advanced'),
    ('dharbacht@msu.edu','Denna','Harbach','F',46,125,32,'Crossfit','Calisthenics','Martial Arts','Beginner'),
    ('nroscriggu@list-manage.com','Neilla','Roscrigg','M',42,103,48,'Pilates','Yoga','Powerlifting','Beginner'),
    ('tillemv@cam.ac.uk','Thurstan','Illem','M',46,119,39,'Swimming','Yoga','Pilates','Advanced'),
    ('ckilloughw@gravatar.com','Cyril','Killough','M',41,88,23,'Spin','Pilates','Martial Arts','Beginner'),
    ('mhuetx@oracle.com','Melly','Huet','M',50,89,6,'Weightlifting','Running','Calisthenics','Beginner'),
    ('ncolquitty@amazon.co.jp','Nedi','Colquitt','F',44,140,31,'Physiotherapy','Weightlifting','Calisthenics','Beginner'),
    ('halldayz@parallels.com','Harlan','Allday','M',50,105,21,'Swimming','Physiotherapy','Pilates','Advanced'),
    ('kpoints10@bigcartel.com','Kienan','Points','M',46,142,16,'Running','Martial Arts','Pilates','Advanced'),
    ('mterrington11@jalbum.net','Melita','Terrington','F',42,124,48,'Powerlifting','Weightlifting','Martial Arts','Advanced'),
    ('wsealeaf12@go.com','Waylan','Sealeaf','F',43,141,48,'Spin','Running','Crossfit','Advanced'),
    ('lirnys13@bbc.co.uk','Luigi','Irnys','F',42,120,32,'Powerlifting','Crossfit','Spin','Intermediate'),
    ('mdundridge14@hhs.gov','Mildred','Dundridge','F',47,135,23,'Running','Calisthenics','Swimming','Intermediate'),
    ('dgrinin15@reference.com','Deonne','Grinin','M',48,150,41,'Martial Arts','Spin','Powerlifting','Intermediate'),
    ('wkuschek16@twitter.com','Winonah','Kuschek','M',40,85,10,'Running','Physiotherapy','Crossfit','Beginner'),
    ('cschorah17@irs.gov','Chloette','Schorah','F',48,80,16,'Martial Arts','Crossfit','Physiotherapy','Beginner'),
    ('ualbrooke18@amazon.co.jp','Ursulina','Albrooke','F',50,85,3,'Yoga','Pilates','Martial Arts','Beginner'),
    ('mhaffenden19@apache.org','Marisa','Haffenden','M',44,124,46,'Running','Powerlifting','Crossfit','Beginner'),
    ('kfrentz1a@g.co','Kenon','Frentz','M',43,114,35,'Physiotherapy','Calisthenics','Crossfit','Intermediate'),
    ('amacartney1b@imageshack.us','Alameda','Macartney','M',40,101,26,'Running','Martial Arts','Swimming','Beginner'),
    ('dbiasetti1c@t-online.de','Druci','Biasetti','F',45,83,3,'Crossfit','Running','Physiotherapy','Advanced'),
    ('lfullager1d@wordpress.org','Liane','Fullager','F',42,115,5,'Calisthenics','Running','Powerlifting','Beginner');
